version: '3.8'

services:
    app:
        build: .
        container_name: nest-streaming-app
        ports:
            - '3000:3000'
        volumes:
            - ./uploadedvideos:/app/uploadedvideos
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    redis:
        image: redis:7-alpine
        container_name: redis-cache
        ports:
            - '6379:6379'
